@baseUrl = http://localhost:8080/api/trips

### get trips
GET {{baseUrl}}

### get trip by id
GET {{baseUrl}}/3

### add trip
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "rocznica",
  "destination": "Majorka",
  "startDate": "2026-09-22",
  "endDate": "2026-09-29"
}

### add another trip
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "konferencja",
  "destination": "Mielno",
  "startDate": "2026-11-11",
  "endDate": "2026-11-22"
}

### delete trip
DELETE {{baseUrl}}/4

### update trip
PUT {{baseUrl}}/3
Content-Type: application/json

{
  "destination": "Budapeszt",
  "startDate": "2026-09-22",
  "endDate": "2026-09-29"
}